name = "Tufte"
license = "MIT"
licenselink = "https://github.com/shawnohare/hugo-tufte/blob/master/LICENSE.md"
description = "A minimalist blog theme using Tufte-css."
homepage = "http://github.com/shawnohare/hugo-tufte"
tags = ["blog", "tufte", "minimal"]
features = ["math", "tufte-css", "tufte"]
min_version = 0.84

authors = [
  {name = "Shawn O'Hare", homepage = "http://www.shawnohare.com"},
  {name = "Slashformotion", homepage = "https://github.com/slashformotiongithub"}
]

[author]
  name = "Shawn O'Hare"
  homepage = "http://www.shawnohare.com"
