themesDir = "../../"

canonifyurls = true
# baseurl = "https://github.com/shawnohare/hugo-tufte"
theme = "hugo-tufte"
title = "Hugo-tufte Theme Example Site"
pygmentsUseClasses=true
[taxonomies]
  category = "categories" 
  group = "groups"
  series = "series"
  tag = "tags"

[params]
  math = true
  subtitle = "Subtitle goes here."
  copyrightHolder = "Copyright Holder"
  showPoweredBy = true
  hidedate = false

# -----------------------------------------------------------------------
# Navigation menu 
# -----------------------------------------------------------------------
[[menu.nav]]
  name = "Home"
  pre = "<i class='fa fa-home fa-lg'></i> "
  weight = -110 
  identifier = "home"
  url = "/"
[[menu.nav]]
  name = "Posts"
  pre = "<i class='fa fa-book fa-lg'></i> "
  weight = -100 
  identifier = "posts"
  url = "/post"
[[menu.nav]]
  name = "Categories"
  pre = "<i class='fa fa-tags fa-lg'></i> "
  weight = -90 
  identifier = "categories"
  url = "/categories"
[[menu.nav]]
  name = "About"
  pre = "<i class='fa fa-info-circle  fa-lg'></i> "
  weight = -80 
  identifier = "about"
  url = "/about"

# -----------------------------------------------------------------------
# Footer menu 
# -----------------------------------------------------------------------
[[menu.footer]]
  name = ""
  pre = "<i class='fa fa-github fa-2x'></i> "
  weight = -100 
  identifier = "github"
  url = "https://github.com/shawnohare/hugo-tufte"
[[menu.footer]]
  name = ""
  pre = "<i class='fa fa-twitter fa-2x'></i> "
  weight = -90 
  identifier = "twitter"
  url = "https://twitter.com"



[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
